---
name: ambassador

cloud: none
aws:
  listenPort: 80
  sslCertificateArn: arn:aws:acm:us-east-1:914373874199:certificate/1d16f0a1-abd5-44b3-8da5-5e06c843fd3d
  useProxyProtocol: true

profiles:
  sandbox0:
    dockerImage: quay.io/datawire/ambassador:0.34.0
    namespace: sbx0
  sandbox1:
    dockerImage: quay.io/datawire/ambassador:0.34.0
    namespace: sbx1
