---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ service.name }}
  namespace: {{ build.profile.namespace }}
  labels:
    app: {{ service.name }}
spec:
  replicas: {{ build.profile.replicas }}
  selector:
    matchLabels:
      app: {{ service.name }}
  template:
    metadata:
      labels:
        app: {{ service.name }}
    spec:
      containers:
        - name: conntest
          image: {{ build.profile.dockerImage }}
          ports:
            - name: http-api
              containerPort: 7000
