---
name: htttp-loadbalance

profiles:
  sandbox0:
    dockerImage: quay.io/datawire/conntest:latest
    namespace: sbx0
    replicas: 5
  sandbox1:
    dockerImage: quay.io/datawire/conntest:latest
    namespace: sbx1
    replicas: 2
