---
apiVersion: v1
kind: Service
metadata:
  name: grpc-basic
  namespace: {{ build.profile.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
  selector:
    app: grpc-basic
