---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: grpc-basic
  namespace: {{ build.profile.namespace }}
spec:
  replicas: {{ build.profile.replicas | default(1) }}
  template:
    metadata:
      labels:
        app: grpc-basic
    spec:
      restartPolicy: Always
      containers:
        - name: grpc-basic
          image: {{ build.images["Dockerfile"] }}
          ports:
            - name: grpc
              containerPort: 50051
