---
name: grpc-basic

profiles:
  stable:
    namespace: stable
    replicas: 3
  edge:
    namespace: edge
    replicas: 3
  development:
    namespace: development
    replicas: 1

branches:
  master: stable
  rc/*: edge
  dev/*: development
